Repository ludoboulanger/rental_app, pull requests merged in 2021-06, with the labels that each got.

#13 [Rent-17] (mobile) header
  client_app/.eslintrc.json
  client_app/package-lock.json
  client_app/package.json
  client_app/public/locales/en/translation.json
  client_app/public/locales/fr/translation.json
  client_app/src/App/App.js
  client_app/src/components/Headers/MobileHeader.jsx
  client_app/src/components/Headers/styles.js
  client_app/src/components/SearchBar/SearchBar.jsx
  client_app/src/components/SearchBar/styles.js
  client_app/src/index.css
  client_app/src/index.js
  client_app/src/pages/Home.js
  client_app/src/pages/SearchPage.js
  client_app/src/pages/SettingsPage.js
  client_app/src/services/ThemeService.js
  client_app/src/utils/enums.js
  client_app/src/utils/queries.js
  package-lock.json
Labels: MVP

#15 Support pour Sign Up
  backend_app/.env.example
  backend_app/api/index.js
  backend_app/api/routes/Authentication.js
  backend_app/api/schemas/accountInfo.json
  backend_app/api/schemas/schemas.js
  backend_app/api/tests/DatabaseMock.js
  backend_app/api/tests/routes.spec.js
  backend_app/api/utils/ErrorHandler.js
  backend_app/migrate-mongo-config.js
  backend_app/migrations/20210518022137-test-migration.js
  backend_app/migrations/20210614111928-accountInfoCollection.js
  backend_app/mongo/AccountInfo.js
  backend_app/mongo/Connection.js
  backend_app/package-lock.json
  backend_app/package.json
  backend_app/readme.md
Labels: MVP

#20 [RENT-17] Desktop header
  client_app/.eslintrc.json
  client_app/src/components/Headers/DesktopHeader.jsx
  client_app/src/components/Headers/MobileHeader.jsx
  client_app/src/components/Headers/index.jsx
  client_app/src/components/Headers/styles.js
  client_app/src/components/SearchBar/styles.js
  client_app/src/pages/Home.js
  client_app/src/services/ThemeService.js
Labels: MVP, frontend

#23 [Rent-45] bottom nav bar
  client_app/src/components/BottomNavigation/index.jsx
  client_app/src/components/Headers/DesktopHeader.jsx
  client_app/src/components/Headers/MobileHeader.jsx
  client_app/src/components/Icon/index.jsx
  client_app/src/components/SearchBar/SearchBar.jsx
  client_app/src/pages/Home.js
  client_app/src/services/ThemeService.js
  client_app/src/utils/enums.js
Labels: MVP, frontend

#26 [Rent-26] create readme
  .gitignore
  README.md
  backend_app/package.json
  client_app/src/components/Headers/index.jsx
  package-lock.json
  package.json
Labels: documentation
